### ISSUE TITLE
Public function "Read-PrivateVariable" to support debugging

### ISSUE THREAD

**Issue by PatrickOnGit** [merddyin/ADDeploy#10]
As many variables are marked as private, debugger can't read their content.
A little helper function running in module context solves this issue.
Add the following function in "Public" folder:

```
function Read-PrivateVariable {
<#
    .SYNOPSIS
        Function that allows to read the variables defined within the module to help with troubleshooting

    .DESCRIPTION
        Function that allows to read the variables defined within the module to help with troubleshooting

    .PARAMETER var
        Variable to check. Returns all variables in Script scope when empty.

    .EXAMPLE
        PS C:\> Read-PrivateVariable 

    .INPUTS
		System.String

    .OUTPUTS
        PowerShellObject

    .NOTES
        Cmdlet Version: 1.0

        Copyright (c) Axians IT Services AG - All rights reserved.

        Use of this source code is subject to the terms of use as outlined in the included LICENSE file, or elsewhere within this file. This
        source code is provided 'AS IS', with NO WARRANTIES either expressed or implied. Use of this code within your environment is done at your
        own risk, and the author assumes no liability.

#>
    Param ( $var )

    if ( $var ) {
        Get-Variable -Name $var -Scope Script | Select -ExpandProperty Value
    } Else {
        Get-Variable -Scope Script
    }

}
```

**Comment by merddyin** [comment]
Which variables are you concerned with? Nearly every variable used during runtime has an associated Write-Verbose statement. The variables that are loaded during import are not visible in this manner, however the updated version of the code that I am still testing provides a function of sorts to address this. It is intended for use by those who would be developing the module however, not for users, to make the built-in data sets more discoverable when someone is building new functionality. Since it's not intended for end users, the build process removes the function.

What would be your use case for making this available to end users?

**Comment by PatrickOnGit** [comment]
The function is actually more for developing and debugging as you mentioned. It is part of the public functions to be used when debugging with ISE or VScode as the variables marked as private are not visible to the debugger. As the code runs for hours in a large environment I added breakpoints that where hit when an exception occured and then checked the data stored in the various variables while everthing was still in memory (as it it the breakpoint and not yet stopped).

**Comment by merddyin** [comment]
Hrmm...in large environments I typically use the orchestration function, which splits everything up into numerous smaller runspaces that all execute concurrently. Not sure how breakpoints would work in that scenario, but I'll look into adding this type of function into the 'dev stack'. Admittedly, I don't tend to use the debugger...I don't really have a developer background at all, just a lot of experience scripting things in basic, DOS, and VBScript, until PowerShell was introduced (as Monad). Now I find myself working to learn C#, so I'm just starting on the whole debugging journey.

If it helps, as I mentioned, I have nearly every variable value getting dumped to Write-Verbose. If memory serves, this version of the module currently doesn't load the nlog plugin, but you can re-enable it and all data should be captured in the resulting log file.

**Comment by merddyin** [comment]
I have gone ahead and added your function to the Dev branch copy of the code. I'll go back later and update the build process to automatically remove the file, along with the Publish-ADDDBMemData cmdlet.

**Comment by PatrickOnGit** [comment]
Cool, thank you.
Btw. I added the module PSFramework into "my" ADDeploy build and three "Proxy" functions, which simply overwrite Write-Warning, Write-Error and Write-Verbose and write all output assynchronous in log files. When logging synchronously, it slows down the script by factor 4. But it also means, do not log of after script was running until the logs are written.
