### ISSUE TITLE
PSSQLite 1.0.3 should be updated to 1.1.0

### ISSUE THREAD

**Issue by PatrickOnGit** [merddyin/ADDeploy#9]
PSSQLite does have several issues which are solved in version 1.1.0 and should replace version 1.0.3 as plugin

**Comment by merddyin** [comment]
This has already occurred in the version I have not checked in yet.

**Comment by merddyin** [comment]
Please see Dev branch, which leverages an updated version of the PSSQLite module, so it uses whatever version of the SQLite DLLs that module uses.

**Comment by PatrickOnGit** [comment]
Perfect
